#include<stdio.h>
#include<stdlib.h>
#include<math.h>
#include<sys/time.h>
#include<sys/wait.h>
#include<unistd.h>
#include<time.h>

int check_prime(int n){
    if(n<2) return 0;

    for(int i =2; i*i<=n ; i++){
        if(n%i==0) return 0;
    }
    return 1;
}

void generate_primes(int start, int end, int n){
    int range = end - start + 1;
    int chunck = range/n;

    struct timespec t_start, t_end;
     
    clock_gettime(CLOCK_MONOTONIC, &t_start);

    for(int i = 0; i<n ; i++){
        pid_t pid = fork();

        if(pid==0){
            int sRange = start + i*chunck;
            int eRange = (i==n-1) ? end : (sRange + chunck - 1);

            char fname[50];
            sprintf(fname, "prime_%d.txt", i);// for each child process
            FILE *fp = fopen(fname, "w");

            for(int j = sRange; j<=eRange; j++){
                if(check_prime(j)){
                    fprintf(fp, "%d\n", j);
                }
            }
            fclose(fp);
            exit(0);
        }
    }

    for(int i =0; i<n; i++){
        wait(NULL);
    }

    clock_gettime(CLOCK_MONOTONIC, &t_end);

    double time_taken = (t_end.tv_sec - t_start.tv_sec) + (t_end.tv_nsec - t_start.tv_nsec) / 1e9;

    FILE *log = fopen("time.txt", "a");// time taken file
    fprintf(log, "%d %d %d %f\n", start, end, n, time_taken);
    fclose(log);

    FILE *final = fopen("prime.txt", "w");

    for(int i = 0; i < n; i++){// merging the primes generated by each of the child
        char fname[50];
        sprintf(fname, "prime_%d.txt", i);

        FILE *fp = fopen(fname, "r");
        int x;
        while(fscanf(fp, "%d", &x) != EOF)
            fprintf(final, "%d\n", x);

        fclose(fp);
    }

    fclose(final);

}

int main(int argc, char *argv[]){
    if(argc != 4){
        printf("Usage: %s start end n\n", argv[0]);
        return 1;
    }

    int start = atoi(argv[1]);
    int end = atoi(argv[2]);
    int n = atoi(argv[3]);

    generate_primes(start, end, n);

    return 0;
}